# Generated by Django 5.0.2 on 2024-02-16 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('day_number', models.PositiveIntegerField()),
                ('notepad', models.TextField()),
                ('highlight', models.TextField()),
                ('blunder', models.TextField()),
                ('references', models.JSONField()),
                ('subtopics', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day100.curriculum')),
            ],
        ),
    ]
