# Generated by Django 5.0.2 on 2024-02-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day100', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='blunder',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='day_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='highlight',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='notepad',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='references',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='subtopics',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
