# Generated by Django 5.0.2 on 2024-02-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day100', '0002_alter_curriculum_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daylog',
            name='blunder',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='highlight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='notepad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
